---
title: "Spectral analysis for biophysical factors"
author: "MOEKA"
date: "2025-03-04"
output: html_document
---

```{r setup, include=FALSE}

```

```{r read csv}
C1 <- read.csv("G:/My Drive/Research/Projects/DC_auto/Data/SR_combined/C1.csv")
C2 <- read.csv("G:/My Drive/Research/Projects/DC_auto/Data/SR_combined/C2.csv")
C3 <- read.csv("G:/My Drive/Research/Projects/DC_auto/Data/SR_combined/C3.csv")
C4 <- read.csv("G:/My Drive/Research/Projects/DC_auto/Data/SR_combined/C4.csv")
C5 <- read.csv("G:/My Drive/Research/Projects/DC_auto/Data/SR_combined/C5.csv")

```

```{r function}
scale_pad_col <- function(df, var1){
  df %>%
    select(date, var1) %>%
    mutate(NA_flag = ifelse(!is.na(df[var1]), "0", "1")) %>%
    mutate(across(where(is.numeric), scale)) %>%
    mutate(across(where(is.numeric), ~replace(., is.na(.), 0)))
}

```


```{r dir}
PAR_dir_pwr <- "G:/My Drive/Research/Projects/DC_auto/Data/Spectral_biophysical/PAR/df_temporal_pwr/"
Ts_dir_pwr <- "G:/My Drive/Research/Projects/DC_auto/Data/Spectral_biophysical/Ts/df_temporal_pwr/"
VWC_dir_pwr <- "G:/My Drive/Research/Projects/DC_auto/Data/Spectral_biophysical/VWC/df_temporal_pwr/"

Mea_per <- c("C1", "C2", "C3", "C4", "C5")
```

```{r WT PAR}

wt_PAR_list <- list()

for(i in Mea_per){
  
  df <- get(i)
  
  # scale
  df1 <- scale_pad_col(df, "PPFD_IN_1_1_1") 

  df2 <- 
    analyze.wavelet(
      df1, "PPFD_IN_1_1_1", 
      loess.span = 0,     ## no detrending required
      dt = 1/24,          ## defines the time unit --- there are 24 slots in a day! Time unit = 1 day
      dj = 1/100,         ## resolution along period axis
      lowerPeriod = 1/4,  ## 6 hour
      upperPeriod = 64,  ## 128 days
      make.pval = T,      ## check for significance
      n.sim = 10         ## 10 white-noise simulations used for assessing significance 
      )
  
  wt_PAR_list[[i]] <- df2
}




PAR_C1_pwr <- wt_avg(wt_PAR_list$C1, 30)
PAR_C2_pwr <- wt_avg(wt_PAR_list$C2, 30)
PAR_C3_pwr <- wt_avg(wt_PAR_list$C3, 30)
PAR_C4_pwr <- wt_avg(wt_PAR_list$C4, 30)
PAR_C5_pwr <- wt_avg(wt_PAR_list$C5, 30)

write.csv(PAR_C1_pwr$df, paste0(PAR_dir_pwr, "C1_PAR.csv"), row.names = F)
write.csv(PAR_C2_pwr$df, paste0(PAR_dir_pwr, "C2_PAR.csv"), row.names = F)
write.csv(PAR_C3_pwr$df, paste0(PAR_dir_pwr, "C3_PAR.csv"), row.names = F)
write.csv(PAR_C4_pwr$df, paste0(PAR_dir_pwr, "C4_PAR.csv"), row.names = F)
write.csv(PAR_C5_pwr$df, paste0(PAR_dir_pwr, "C5_PAR.csv"), row.names = F)
```


```{r WT Ts}

wt_Ts_list <- list()

for(i in Mea_per){
  
  df <- get(i)
  
  # scale
  df1 <- scale_pad_col(df, "TS_1_1_1") 

  df2 <- 
    analyze.wavelet(
      df1, "TS_1_1_1", 
      loess.span = 0,     ## no detrending required
      dt = 1/24,          ## defines the time unit --- there are 24 slots in a day! Time unit = 1 day
      dj = 1/100,         ## resolution along period axis
      lowerPeriod = 1/4,  ## 6 hour
      upperPeriod = 64,  ## 128 days
      make.pval = T,      ## check for significance
      n.sim = 10         ## 10 white-noise simulations used for assessing significance 
      )
  
  wt_Ts_list[[i]] <- df2
}



Ts_C1_pwr <- wt_avg(wt_Ts_list$C1, 20)
Ts_C2_pwr <- wt_avg(wt_Ts_list$C2, 20)
Ts_C3_pwr <- wt_avg(wt_Ts_list$C3, 20)
Ts_C4_pwr <- wt_avg(wt_Ts_list$C4, 20)
Ts_C5_pwr <- wt_avg(wt_Ts_list$C5, 20)

write.csv(Ts_C1_pwr$df, paste0(Ts_dir_pwr, "C1_Ts.csv"), row.names = F)
write.csv(Ts_C2_pwr$df, paste0(Ts_dir_pwr, "C2_Ts.csv"), row.names = F)
write.csv(Ts_C3_pwr$df, paste0(Ts_dir_pwr, "C3_Ts.csv"), row.names = F)
write.csv(Ts_C4_pwr$df, paste0(Ts_dir_pwr, "C4_Ts.csv"), row.names = F)
write.csv(Ts_C5_pwr$df, paste0(Ts_dir_pwr, "C5_Ts.csv"), row.names = F)
```


```{r WT VWC}

wt_VWC_list <- list()

for(i in Mea_per){
  
  df <- get(i)
  
  # scale
  df1 <- scale_pad_col(df, "SWC_1_1_1") 

  df2 <- 
    analyze.wavelet(
      df1, "SWC_1_1_1", 
      loess.span = 0,     ## no detrending required
      dt = 1/24,          ## defines the time unit --- there are 24 slots in a day! Time unit = 1 day
      dj = 1/100,         ## resolution along period axis
      lowerPeriod = 1/4,  ## 6 hour
      upperPeriod = 64,  ## 128 days
      make.pval = T,      ## check for significance
      n.sim = 10         ## 10 white-noise simulations used for assessing significance 
      )
  
  wt_VWC_list[[i]] <- df2
}



VWC_C1_pwr <- wt_avg(wt_VWC_list$C1, 20)
VWC_C2_pwr <- wt_avg(wt_VWC_list$C2, 20)
VWC_C3_pwr <- wt_avg(wt_VWC_list$C3, 20)
VWC_C4_pwr <- wt_avg(wt_VWC_list$C4, 20)
VWC_C5_pwr <- wt_avg(wt_VWC_list$C5, 20)

write.csv(VWC_C1_pwr$df, paste0(VWC_dir_pwr, "C1_VWC.csv"), row.names = F)
write.csv(VWC_C2_pwr$df, paste0(VWC_dir_pwr, "C2_VWC.csv"), row.names = F)
write.csv(VWC_C3_pwr$df, paste0(VWC_dir_pwr, "C3_VWC.csv"), row.names = F)
write.csv(VWC_C4_pwr$df, paste0(VWC_dir_pwr, "C4_VWC.csv"), row.names = F)
write.csv(VWC_C5_pwr$df, paste0(VWC_dir_pwr, "C5_VWC.csv"), row.names = F)
```




```{r making dfs for diurnal peaks}
temp_pwr_csv <- function(filename){
  
  df <- strsplit(filename, "/")[[1]][10]
  season <- 
    ifelse(
      is.na(strsplit(df, "_")[[1]][4]) == T, 
      sub(".csv", "", strsplit(df, "_")[[1]][3]), 
      sub(".csv", "", strsplit(df, "_")[[1]][4])
      )
  resp <- strsplit(df, "_")[[1]][2]
  driver <- 
    ifelse(
      is.na(strsplit(df, "_")[[1]][4]) == T, 
      NA, 
      strsplit(df, "_")[[1]][3]
      )
  
  result <- 
    read.csv(filename) %>%
    summarise(
      pwr_P1 = Power.avg[Period == "1"],
      pwr_max = max(Power.avg, na.rm = TRUE),
      pwr_max_period = Period[which.max(Power.avg)]) %>% 
    mutate(
      df = df,
      season = season,
      resp = resp,
      driver = driver
    ) 
}


res_pwr <- purrr::map_dfr(filenames_res_pwr, temp_pwr_csv)


                              
# csv
write.csv(res_pwr, "G:/My Drive/Research/Projects/DC_auto/Data/Nov2024_rerun/Re_temp_pwr_res.csv", row.names = F)

raw_pwr <- purrr::map_dfr(filenames_raw_pwr, temp_pwr_csv)
par_phase$season <- 
  factor(par_phase$season, levels = c("May22", "Mar23", "Jan24", "Feb24", "Mar24"))

# csv
write.csv(raw_pwr, "G:/My Drive/Research/Projects/DC_auto/Data/Nov2024_rerun/temp_pwr_raw.csv", row.names = F)


```


```{r}
filenames_PAR <- list.files(PAR_dir_pwr, "*.csv", full.names = T)
filenames_Ts <- list.files(Ts_dir_pwr, "*.csv", full.names = T)
filenames_VWC <- list.files(VWC_dir_pwr, "*.csv", full.names = T)
```


```{r making plots}
temp_pwr_plot_WT <- function(filename, file_des){
  
  plot_list <- list()
  
  for (i in filename){
    
    df <- strsplit(i, "/")[[1]][length(strsplit(i, "/")[[1]])]
    driver <- sub("\\.csv$", "",strsplit(df, "_")[[1]][2])
    campaign <- strsplit(df, "_")[[1]][1]
    
    p1 <- 
      read.csv(i) %>%
      ggplot() +
        geom_line(aes(log2(Period), Power.avg)) +
        geom_point(aes(log2(Period), Power.avg.sig), size = 1) + 
        theme_classic() + 
        #ylab("Avg. Wavelet Spectram") + 
        #xlab("Period (days; log scale)") +
        #ggtitle(paste(resp, "vs", driver, season, sep = " ")) +
        scale_x_continuous(
            breaks = c(0, 3, 6),
            label = c(1, 8, 64)
        ) +
        scale_y_continuous(
            breaks = c(0, 10, 20),
            limits = c(0, 20)
        ) +
        theme(
            axis.title.x = element_blank(), 
            axis.text.x = element_text(size = 10),
            axis.title.y = element_blank(),
            axis.text.y = element_text(size = 10),
            legend.title = element_text(size = 10), 
            legend.text = element_text(size = 10),
            panel.border = element_rect(colour = "black", fill = NA, linewidth = .5)
        )
    plot_list[[i]] = p1
  }
  
  for (i in filename) {
    
    df <- strsplit(i, "/")[[1]][length(strsplit(i, "/")[[1]])]
    driver <- sub("\\.csv$", "",strsplit(df, "_")[[1]][2])
    campaign <- strsplit(df, "_")[[1]][1]
    
    file_name = 
      file.path(
        file_des,
        paste0(campaign, "_", driver, ".png")
        )
      
    png(file_name, width = 560, height = 450, res = 300)
    print(plot_list[[i]])
    dev.off()
  }
}


temp_PAR_plt <- 
  temp_pwr_plot_WT(filenames_PAR, "G:/My Drive/Research/Projects/DC_auto/Data/Spectral_biophysical/PAR/img_temp_pwr/")

temp_Ts_plt <- 
  temp_pwr_plot_WT(filenames_Ts, "G:/My Drive/Research/Projects/DC_auto/Data/Spectral_biophysical/Ts/img_temp_pwr/")

temp_VWC_pwr_plt <- 
  temp_pwr_plot_WT(filenames_VWC, "G:/My Drive/Research/Projects/DC_auto/Data/Spectral_biophysical/VWC/img_temp_pwr/")

```